### ISSUE TITLE
Make it easier to close the Overlay window

### ISSUE THREAD

**Issue by matfantinel** [DevAlien/workspaces#14]
Currently, when I use the shortcut to bring up the Overlay and select a workspace to open, the overlay window stays there. To close it, I have to focus on the search bar and then press Esc:

![Current Behavior](https://user-images.githubusercontent.com/24247035/91738318-a97e6780-eb86-11ea-9b97-d6504bfefc00.gif)

This makes it hard to close the window, and, in my example (which just opens the Calculator app), it hides the opened app, which makes me think the action didn't work.

Planner on AppCenter also has a shortcut + overlay flow, and it's easier to close it. It has both a "Cancel" button, and also gets closed when you click outside of the window:

![Desired Behavior](https://user-images.githubusercontent.com/24247035/91738509-efd3c680-eb86-11ea-89d3-bbf442fa7d54.gif)

I think this is a much more intuitive flow, specially if the overlay also closes if a Workspace is selected too. I understand this might be an issue if the user wants to open multiple Workspaces though.

**Comment by matfantinel** [comment]
Planner seems to handle the "click-outside" event on line 272 here: https://github.com/alainm23/planner/blob/master/src/QuickAdd/MainWindow.vala

**Comment by DevAlien** [comment]
Thanks for the report, the click-outside is interesting, I can probably integrate that. but in the case of the calculator is still a stange behaviour. 
What do you think of having the click-outside and then when you click or press enter on an item, it automatically closes it.

But if you do CTRL + click or CTRL + Enter it will stay open, so that you can launch more stuff. 

Would be cool if it could keep the focus as well.

**Comment by matfantinel** [comment]
I really like the idea! Could be also made more discoverable through a tooltip.

Also, about the Calculator opening up behind the overlay, that might be a Gala bug. I had that happen before, specially with the Mail app (when opened from a notification, it doesn't show up immediatelly, and has a red dot on the dock)

**Comment by DevAlien** [comment]
Yes, I will probably go the way with the control. It stays behind because I made the app to stay in front of everything else (like a message dialog)
