### ISSUE TITLE
Change recommended for AppCenter: Don't repeat app name in AppData Summary

### ISSUE THREAD

**Issue by cassidyjames** [DevAlien/workspaces#15]
It's not strictly required, but we recommend you don't repeat your app's name in its summary or in the first sentence of your description. This is super valuable space, so repeating the app name (which will always be displayed largely immediately above the summary) is a waste of that real estate for you, and becomes repetitive for users.

https://github.com/DevAlien/workspaces/blob/06ba6f871c58b1b364067d130481115c3262c134/data/com.github.devalien.workspaces.appdata.xml.in#L8

I would probably recommend the shorter, "Always be ready for work" tagline here.

**Comment by DevAlien** [comment]
Thanks, I've changed it, as your suggestion
