### ISSUE TITLE
Change required for AppCenter: 2.1.1 release does not exist

### ISSUE THREAD

**Issue by cassidyjames** [DevAlien/workspaces#16]
It looks like you submitted a 2.1.1 release to AppCenter, then deleted or renamed that in GitHub. To ensure reproducible builds, AppCenter treats each release as immutable—as such, we cannot accept this build as-is. 

Note that since AppCenter is build on semver versioning, version numbers can only ever increase. As such, you will need to submit a new release with a semver version > 2.1.1.

**Comment by DevAlien** [comment]
@cassidyjames I have released 3.0.0 and sent to appcenter for review
