### ISSUE TITLE
Flatpak apps missing in App Chooser

### ISSUE THREAD

**Issue by louis77** [DevAlien/workspaces#19]
I run Ubuntu 20.04 and use Flatpak for many apps.
Workspace v3.0.0 was also installed via Flatpak, but I don't see the other Flatpak apps in the App Chooser.

**Comment by Philip-Scott** [comment]
Feels like a duplicate of https://github.com/DevAlien/workspaces/issues/12 :)

**Comment by DevAlien** [comment]
Yes, this one should be solved in #12 closing for now
