### ISSUE TITLE
Cannot delete an empty workspace

### ISSUE THREAD

**Issue by louis77** [DevAlien/workspaces#20]
Here you see two Workspaces:

![Screenshot from 2020-09-01 20-44-20](https://user-images.githubusercontent.com/1240462/91893069-ec7a3100-ec93-11ea-99ed-88510fb1366e.png)

But in the Preferences, I see only one:

![Screenshot from 2020-09-01 20-44-52](https://user-images.githubusercontent.com/1240462/91893150-fe5bd400-ec93-11ea-9bec-61221eb59522.png)

How can I delete the "My Workspace"?

This is what I tried:

1. I added an Item in the "My Workspace" which still exists in the dropdown.
2. Right click on "My Workspace" shows a context menu with "Delete"
3. Click "Delete" doesn't actually delete the "My Workspace"
4. When I do the same on the Item, the "My Workspace" disappears again (only in the Preferences)

What I would expect:

1. Right-click on a Workspace and click Delete should delete the workspace and all items in it
2. The workspace should not be displayed any more in the Launcher or dropdowns
3. If I delete the last item from a Workspace, I would say that Workspace should go away since there is no data assosicated with it any more

**Comment by Philip-Scott** [comment]
Can confirm. Looks like the data file in `~/.local/share/com.github.devalien.workspaces/data.json` keeps the empty workspace without any items.

**Comment by DevAlien** [comment]
Yeah that's because the sourcelist from granite is not displayed if it does not have any child. That sucks! I will probbaly need to rethink the left side of the app

**Comment by DevAlien** [comment]
This will now be possible in release 3.1, it is in the develop branch at the moment. Here you can see the improvements.
https://github.com/DevAlien/workspaces/issues/32
