### ISSUE TITLE
App Chooser only shows first few apps, cannot load more

### ISSUE THREAD

**Issue by louis77** [DevAlien/workspaces#22]
![Peek 2020-09-01 21-00](https://user-images.githubusercontent.com/1240462/91894592-3bc16100-ec96-11ea-8f8e-7dbdbcdac240.gif)

**Comment by DevAlien** [comment]
I will load all the apps all at once. like you suggested here: https://github.com/DevAlien/workspaces/issues/18

**Comment by DevAlien** [comment]
loading a ton of icons slows down the first launch. I have limited it to 200, which should be enough for most apps. if you have many you want to filte instead of scrolling
