### ISSUE TITLE
Icons on Workspaces

### ISSUE THREAD

**Issue by Philip-Scott** [DevAlien/workspaces#26]
First of all, awesome work on your app man! I've been using it as a launcher for my work "workspace" and it's wonderful :) 

Having icons on the workspace could also be a cool way for users to visualize the workspace that you are trying to launch. You might need an edit view to edit the workspace as well though.... 

Congrats on the app, and awesome work!

**Comment by DevAlien** [comment]
Hey man, thanks for this, appreciated. Yes I want to add the editor for Workspaces but the problem is that I used the sourcelist from granite. And can't add buttons. I might switch to a normal list or just make edit with right click.

**Comment by DevAlien** [comment]
I have this on develop branch. You can check all the improvements in that branch here: https://github.com/DevAlien/workspaces/issues/32
