### ISSUE TITLE
Feature: Integrate with Planner to launch a selected project

### ISSUE THREAD

**Issue by dar5hak** [DevAlien/workspaces#28]
It would be nice if Workspaces could open Planner (provided it is installed) with a specific project preselected. This would make for a brilliant workflow where you can see your list of tasks right when you open a workspace and would probably be one of the most exemplary inter-app integrations in the elementary OS ecosystem.

This will likely require passing some kind of request through Contractor, and some work on Planner side as well. Of course, it needs a lot of effort on design and development side, but I'm posting to see the interest level and start a conversation if needed. I can lend a hand on development too.

**Comment by DevAlien** [comment]
Thanks for the request. I personally don't use Planner, would you mind opening an issue there as well to see if this would be even possible?

**Comment by DevAlien** [comment]
To accommodate this we can add a way to add extra params to the application. So you would select an application =>planner and then in a field extraparams we can pass the param that Planner expects to open itself on a preselected project

**Comment by dar5hak** [comment]
That makes a lot of sense. It would support all applications which accept CLI arguments.

**Comment by dar5hak** [comment]
alainm23/planner#505 obviates this.
