### ISSUE TITLE
Feature Request: Flathub Release

### ISSUE THREAD

**Issue by BeatLink** [DevAlien/workspaces#30]
Hey there, about to check out the app but the concept seems really interesting. It would be so great if you guys could release this on flathub, then it could be installed on hundreds of other distros. Flatpak even has an elemantary os base app that you can build from.

**Comment by DevAlien** [comment]
Hi @BeatLink the app is already on flathub https://flathub.org/apps/details/com.github.devalien.workspaces

Does it work for you? There are a couple of bugs using the flatpak version but should be mostly working.

**Comment by BeatLink** [comment]
I'll check it out!

**Comment by DevAlien** [comment]
@BeatLink does it work for you?

**Comment by BeatLink** [comment]
Yeah it does!

**Comment by DevAlien** [comment]
Ok, closing it then
