### ISSUE TITLE
Cannot to delete Workspaces

### ISSUE THREAD

**Issue by axvrma** [DevAlien/workspaces#40]
Preferences > [Right Click on workspace name] > delete.

Nothing happens.

**Comment by DevAlien** [comment]
Hi @mrcreatist are you on elementary? if yes, i just wrapped up a new version https://github.com/DevAlien/workspaces/releases/tag/3.1.0 but is not yet in the appcenter, will take few days.

**Comment by axvrma** [comment]
> Hi @mrcreatist are you on elementary? if yes, i just wrapped up a new version https://github.com/DevAlien/workspaces/releases/tag/3.1.0 but is not yet in the appcenter, will take few days.

Yes @DevAlien I am on Elementary OS, I installed it via AppCenter. When could I expect update from AppCenter?

**Comment by DevAlien** [comment]
In the following few days hopefully, there's a bug on a new feature and I have to fix it.

**Comment by DevAlien** [comment]
The app has been sent for review, I hope it will be quick, so when you'll get the update you will have all the new changes. A side from deleting a workspace, you can also edit it, add an icon, sort them with drag and drop, move the items around etc

**Comment by DevAlien** [comment]
@mrcreatist the app is live in the appcenter, could you please check if this is solved for you now?

**Comment by axvrma** [comment]
Hi @DevAlien I updated it just now and it works like breeze. It's an awesome utility tool for my daily work routine.

**Comment by DevAlien** [comment]
Glad it works. I'm happy you enjoy it. Do not hesitate to open new issues with requests in the future. I'm happy to improve it
