### ISSUE TITLE
Workspaces not in Elementary AppCenter by default

### ISSUE THREAD

**Issue by JohnDumpling** [DevAlien/workspaces#60]
After the release of Elementary OS 6, Workspaces is no longer available in the AppCenter. After installing a random Flatpak app from Flathub, the repository is added to the AppCenter and Workspaces show up as a non-curated app. Could you please publish this app to AppCenter? Many thanks.

(Dark theme and rounded corners are also missing.)

**Comment by DevAlien** [comment]
I literally have it dark in Elementary os 5, so probably they changed something in this latest iteration.

Unfortunately lately I have no time to work on this. I also don't know if it makes sense to make specific code for elementary os or just release it for "gnome" on flathub

**Comment by JohnDumpling** [comment]
I respect your decision to not include your app in AppCenter and publish it as a Gnome app. I just really hope that AppCenter isn't going the way of Windows Store from Windows 8-10 era - extremely restricted, impossible to develop apps with tighter system integration, resulting in an extremely small amount of useful apps.

**Comment by ChildishGiant** [comment]
Apps are easier to add than before, it just requires making a PR to [elementary/appcenter-reviews](https://github.com/elementary/appcenter-reviews) with a flatpak manifest. You don't need to update to support Odin dark theme or anything else but if you wish to it's a change of a few lines. https://docs.elementary.io/develop/apis/color-scheme
